import Head from "next/head";
import Featured from "../components/home-page/featured-posts";
import Hero from "../components/home-page/hero";
import { featuredPosts } from "../lib/post-util";

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <Featured posts={props.posts} />
    </>
  );
}

export function getStaticProps() {
  const featured = featuredPosts();

  return {
    props: {
      posts: featured,
    },

    revalidate: 100,
  };
}
